[package]
name = "rand_gen"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "rand_gen"
crate-type = ["cdylib"]

[dependencies]
libc = "0.2.101"
rand = "0.8.4"